# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0002_auto_20171020_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='classifiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='nb_inconsistent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('ontology', 'submission_id')]),
        ),
    ]
