# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0003_auto_20171021_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='publication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
