# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0005_auto_20171021_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='acronym',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
