# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0006_auto_20171022_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ontology',
            options={'verbose_name_plural': 'Ontologies'},
        ),
        migrations.AlterField(
            model_name='submission',
            name='avg_children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_depth',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nb_classes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nb_individuals',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nb_properties',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
