# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0008_auto_20171023_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontology',
            name='port',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
