# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0009_ontology_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='port',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
