# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0010_auto_20171023_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontology',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
