# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0011_ontology_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='version',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
