# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0013_ontology_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
