# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberowl', '0016_auto_20171031_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontology',
            name='nb_servers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
