FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.0
LABEL maintainer <maxat.kulmanov@kaust.edu.sa>

RUN elasticsearch-plugin install https://github.com/coolmaksat/fast-elasticsearch-vector-scoring/releases/download/v5.6.0/elasticsearch-binary-vector-scoring-5.6.0.zip
